### ISSUE TITLE
Provide the Ability to Manually Clear Coverage (for single file)

### ISSUE THREAD

**Issue by amw-zero** [danmayer/coverband#217]
The main use case for manually clearing the coverage for a file is for when the caller of a class changes, but the implementation of the class does not. An example of that is when the caller passes data differently into a method and a branch in that method stops being taken.

In this case, it would be useful to be able to manually clear the coverage that way you can start recollecting it after the calling code changes to verify its effect on the called code.

**Comment by kbaum** [comment]
@amw-zero - it is currently possible to clear the coverage via the rake task:

https://github.com/danmayer/coverband#clear-coverage

Or via the web endpoint assuming Configuration#web_enable_clear is enabled (default is false).

https://github.com/danmayer/coverband#clear-coverage

Is there something else you were picturing or does this meet your needs?

**Comment by danmayer** [comment]
Thanks for responding @kbaum I was going to recommend the same things. Are you looking for a way to clear a single file? If so that isn't something we have done before clear everything is the only option at the moment, but if you are requesting that it would be good to know how often that is needed vs clearing all.

* I am closing this other ticket as a duplicate https://github.com/danmayer/coverband/issues/216
* somehow your example receiving code never got posted to either ticket, but I think I get the ideas

**Comment by amw-zero** [comment]
I think clearing a single file would be useful. Wiping all of the coverage data would lose valuable info across the codebase. In my case, I have a very specific file that I’d like to clear because I believe some code is not getting hit anymore in it.

**Comment by danmayer** [comment]
OK, thanks @amw-zero for now clearing all is the only method, but I can look at adding this feature to the roadmap. I am thinking on the individual file page @kbaum we could have a button at the top to reset file coverage.

**Comment by kbaum** [comment]
I like that idea. This seems like it would be a common use case.

**Comment by danmayer** [comment]
this is now on the 4.2.0 branch

**Comment by danmayer** [comment]
closing as this is on master and the 4.2.0.rc2 release

**Comment by danmayer** [comment]
OK @amw-zero if you check out the 4.2.0 release this is now fixed https://github.com/danmayer/coverband/blob/master/changes.md#coverband-420
