### ISSUE TITLE
Line Counter Never Goes Above 1

### ISSUE THREAD

**Issue by hlin-blurb** [danmayer/coverband#23]
1) I run rake coverband:clear, coverband:baseline, coverband:coverage
2) I check that Coverband says my method foobar was not executed
3) I go to a page that executes foobar
4) I run coverband:coverage and check that Coverband says foobar has been executed once
5) I go to that page that executes foobar again (with old/new cookies, in the same/different browser, doesn't matter)
6) I run coverband:coverage, and Coverband tells me foobar was still only executed once.

In fact, I can't seem to get any part of a model or view to report an execution count > 1. Have you ever experienced this?

**Comment by danmayer** [comment]
So the way coverband was setup. It was only intended to show 0 or 1 if code was executed or not. It wasn't trying to keep execution count. Now there has been talk of adding that feature, but it will never be fully accurate for a variety of reasons and could increase the performance costs of running Coverband. 

Basically, Coverband is most often run on a sampling percentage of requests so it would only do counts when it is sampling. Then for perf we have been caching lines and not incrementing the counter once a line was hit. There would still be value of a counter even if it was sampling based as it would show the highest utilized files and methods. I could look into this and measure the impact to performance.

Would you find this feature useful even if the number wasn't a completely accurate hit count, and more just an estimate of code usage?

**Comment by atuel** [comment]
Looking at the Coverband::Base class, it looks like you already track this info and report it in verbose mode.  Just its never sent over to redis and as such is essentially stripped by the time the Reporter class generates a report as it only relies on data from redis.

When coverband isnt running in sampling mode, the number being tracked would be accurate right?  There are potentially some thread safety issues if using a multithreaded test case, but as long as its single threaded, should be accurate right? 

Even in sample mode, the number would still be accurate (outside of thread safety issues) I would think.  It just has a slightly different meaning as it was not the number of times the method was executed but rather the number of times it was captured in a sample right?

**Comment by danmayer** [comment]
yeah if you aren't sampling at all it would be accurate. With sampling on it would give you a relative count based on the sample rate as a estimate. 

Right now I cache around sending to redis to reduce the performance impact of trying to send to much over. I could optionally allow repeated counts, which would allow the kind of data you are talking about. 

I mostly considered the binary hit and not hit to be the most important for finding duplicated code. The use case for estimated or exact counts seems a little more fuzzy, it would let you know which code was executed the most to focus tests or focus refactoring efforts? I am just not sure if the value of the data is worth the effort. Do you have specific thoughts on what you want to use it for @atuel or @hlin-blurb

**Comment by atuel** [comment]
In addition to using coverband to find dead code, I've found it has some advantages over other coverage tools in unit and integration testing.  Most other tools rely the ruby coverage functionality which dont catch how some frameworks load ruby code.  Coverband is able to catch these since it does the coverage detection differently. So the use case is similar to the use case it would be when using other coverage tools.... namely a metric in evaluating test quality, etc.  

In this scenario, overhead isnt all that important as its not prod.   Its a production like run in integration testing, but it can run slow without issue.  

Coverband has the huge advantage that it actually detects the code thats loaded in in ways other than via require, etc.  Unfortunately, the other coverage tools have 2-3 advantages/features over coverband... line execution counts being one.  I wrote a simple hack that doesnt clear out the line counts on a save and then looks those up in the reporter passing that data on to simplecov rather than a hard coded 1.  Seems to report data pretty well, but I didnt take it as far as to push that data into redis.

The second most annoying thing is that the others that rely on ruby's coverage library also get free evaluation of unexecutable lines (ie lines with white space and else or end type lines).   This helps weed out what has amounted to non-trivial number of lines for me in the high level reports and saves the time of manually having to scroll through looking at a bunch of red lines that will never show as executed as ruby never evaluates them.  I was able to write a little regex in the reporter to catch a lot of these type of lines and minimize overhead by only running it during the report and only for lines that didnt actually execute.

The third is both a advantage and disadvantage... that is the use of redis.  On one hand, its nice to store that data centrally, but on the other hand, it requires additional setup.  Since some of my scenarios that I'm trying to do coverage for are provisioning new VMs, I dont always have redis easily available to me to use initially.  It would be nice on these scenarios to have a local only mode that doesnt use redis.  The verbose reporting is very close to this, but I'd like the simplecov report to work as well and right now that looks at redis only.  I havent looked too closely at it, but didnt see a super quick way around it.

So thats the use case I'm looking at... some maybe slightly off topic of the opening issue, but including it to show the full use case I'm looking at.

**Comment by danmayer** [comment]
I will be looking at some improvements to coverband in the next while. I think supporting this outside of dev debug mode could be cool. I will look at that.

**Comment by danmayer** [comment]
this was resolved by @guigs I had previously avoided this mostly due to performance concerns but he added support while also making coverband faster ;)

**Comment by guigs** [comment]
We still need to store line counts in redis https://github.com/danmayer/coverband/pull/75#issuecomment-264827096

**Comment by danmayer** [comment]
@guigs you can see first working version, but I need to do some serious cleanup which I outlines in my on hold PR https://github.com/danmayer/coverband/pull/79

**Comment by danmayer** [comment]
Alright this is live as 1.5.0 closing this out!
