### ISSUE TITLE
Rake coverband:coverage task no longer working

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#234]
Version: 4.2.0.rc2

Run `rake coverband:coverage` and see no output to reproduce.

thx.

**Comment by kbaum** [comment]
Just thinking about this one. Would it make sense to support this task by just starting a rack server locally and serving the report in the same way we do when it's embedded in rails app? This might simplify things.

**Comment by danmayer** [comment]
hmm interesting idea @kbaum could be nice in terms of having a single experience. 

honestly, the fix is easy I am more concerned with figuring out some good tests to catch this... The tests around the reporting need to be reworked as we add more front end complexity.

The fix is to pass in a new var from the HTML Reporter, to set if we are static or dynamic... `static = true` or something.

Then update https://github.com/danmayer/coverband/blob/master/views/layout.erb#L51 to something like:

```
  <%= static ? formatted_source_file(result, source_file) : formatted_source_file_loader(result, source_file) %>
```

**Comment by danmayer** [comment]
I guess not well named, but we already from the reporter call two different paths and we can tell static or dynamic based on `base_path` this is already used to handle how we render assets differently

https://github.com/danmayer/coverband/blob/master/lib/coverband/utils/html_formatter.rb#L79

**Comment by kbaum** [comment]
If it's a quick fix, i can see just moving forward with it for now. In terms of testing, we could punt and longer term move towards reporting always being a rack server. Then we could go with a capybara style feature test for it. 

The downside of having only a rack server is that we wouldn't be supporting use cases of serving the report from s3 or a continuous build services.  In my case since our rails instance in production is api only, I would just run the rack server locally and point REDIS_URL at production. That works assuming REDIS is not behind a production firewall.

**Comment by danmayer** [comment]
resolved
