### ISSUE TITLE
Is coverband useful for evaluating line coverage in the views of a rails project?

### ISSUE THREAD

**Issue by cawel** [danmayer/coverband#25]
The main reason why I decided to give coverband a try is to be able to delete useless code located in the views of a rails project. The report generated after 1 or 2 requests on my app shows various coverage for the touched controllers and models, but shows 100% coverage for *all* the views touched. However, I know this is not the case (I have if/else blocks in some of those views, and I know for sure that both branches of those if/else blocks could not have been touched). My impression is that as long as 1 line of a view is "touched", the report will say the whole view has been 100% covered. 

Also, from the readme – although probably not directly related to my issue – I can read:

> the line numbers reported for ERB files are often off and aren't considered useful. I recommend filtering out .erb using the config.ignore option.

My question: is coverband an appropriate tool to evaluate line coverage in my rails views?

**Comment by danmayer** [comment]
no sorry it can't help with the views. The issue is that compile views have different line numbers and the coverage doesn't match up in a way that I can accurately report what is seen in views. For views you might want to try [flatfoot](https://github.com/livingsocial/flatfoot) although it doesn't give line by line usage it is only at the layout, template, partial level. 

Coverband is more for the backend code than the frontend.

**Comment by cawel** [comment]
Thanks for the gem recommendation, I'll give `flatfoot` a try. 

As for coverband, even if the coverage figure is inaccurate for the views (100% for each view), I can still use the generated report, go into my views one by one, and get an idea of what ruby lines were never executed. So that's a start for my mission to clean up the views. Thanks!

**Comment by danmayer** [comment]
Cool glad it can be helpful.
