### ISSUE TITLE
What do the report columns mean?

### ISSUE THREAD

**Issue by jjb** [danmayer/coverband#312]
Is it documented somewhere what each report column means? Let me know what they are and I'll make a PR adding the info to the readme. Thanks!

**Comment by kbaum** [comment]
Great point.

- **% covered** - Percentage of total relevant lines covered
- **% runtime** - Percentage of the runtime lines covered where runtime lines are lines that are hit after the application has been eagerly loaded
- **Lines** - total lines in the file including lines unreachable or uncover-able. An unreachable line would be an empty line with no code.
- **Relevant lines** - lines that are coverable - not empty
- **Lines runtime** - Total lines minus uncoverable lines minus the lines that are only hit during eager loading of application
- **Lines missed** - relevant lines not covered
- **Avg hits/line** - Total of coverage to the file divided by relevant lines. 

@danmayer - correct me if I am off on any of these.

We might want to revisit these at some point. Would be interesting to know what people feel is relevant to them.

**Comment by danmayer** [comment]
yeah I guess a few thoughts on how to make this easier to understand.... add the above to the readme? Add hover tool tips?

**Comment by jjb** [comment]
Wow, thanks for all the info!

What does coverable mean? I think I know what reachable means, but just in case, could you define that as well.

**Comment by kbaum** [comment]
I am using the words reachable and coverable synonymously here.

**Comment by jjb** [comment]
haha, gotcha!

So does reachable/coverable means that coverband is able to look at it?

I thought that reachable meant if it was possible for the code to ever be executed? e.g.

```ruby
if thing
  …
elsif !thing
  …
else
  # this code can never be executed
end
```

**Comment by kbaum** [comment]
Coverband depends on ruby's coverage library which let's you know if there's any code on a line. Lines that have no code (empty or just comments) are not "reachable".

The white lines in this picture are not "reachable".

![image](https://user-images.githubusercontent.com/96786/63116863-a1965a00-bf68-11e9-98af-3a5997d25a91.png)

Looks like `end` statements are not reachable either.

**Comment by jjb** [comment]
thanks! I started this wiki doc https://github.com/danmayer/coverband/wiki/Dictionary

**Comment by jjb** [comment]
> The white lines in this picture are not "reachable".

what are the red lines? code that hasn't been executed at runtime?

Are red lines always covered/reachable? If so, it seems like % runtime is pretty much the only important metric? Maybe it should go furthest to the left?

**Comment by kbaum** [comment]
Green is covered lines
Red lines are reachable but not covered.

Agree that %runtime is the most important metric.

**Comment by jjb** [comment]
> I am using the words reachable and coverable synonymously here.

> Red lines are reachable but not covered

so they are coverable, but not covered? meaning coverband is able to observe if they were executed, and they were in fact not executed?

**Comment by kbaum** [comment]
That sounds right to me.

**Comment by jjb** [comment]
I have a file with these stats:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/6097/63536816-6228ba00-c4e2-11e9-82c0-306a19dcc0f5.png">

it looks like this:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6097/63536940-a5832880-c4e2-11e9-9df8-3379fde1aca5.png">

I thought that 100% covered, 0% runtime means that we are able to observe all the lines, and none of them were run at runtime. But the code visualization seems to indicate something else. What's the green mean? Does it mean something different/wrong because it's a module?

Thanks!

**Comment by kbaum** [comment]
The green just means the lines were covered. The report is saying that all of these lines were hit during eager load of the application. Would that make sense?

**Comment by jjb** [comment]
So there's no way to know if the lines were executed after eager load, right? (sorry if I'm being slow… I feel an ah-ha moment coming on...)

**Comment by kbaum** [comment]
If there are runtime hits, they should appear in the report:

![image](https://user-images.githubusercontent.com/96786/63541229-aa98a580-c4eb-11e9-8eb8-c004fe1369db.png)

**Comment by jjb** [comment]
ahhhh okay. cool cool cool

**Comment by blakewest** [comment]
Hi, @kbaum  thanks for the info here. I'm running into a related problem, which is that the report appears to mark many lines as "unreachable", when I can absolutely guarantee the lines are both eager-loaded, and run at run-time. See the code below, where you can see a method definition is white, and marked as unreachable.

![image](https://user-images.githubusercontent.com/2524396/64935468-4a550500-d806-11e9-8f73-30d40f8327c1.png)

This particular example is a method inside of a base class that gets subclassed many times. But the base method in the picture is never over-written in any of the subclasses. And I know for sure it gets run all the time in the main app. 

Here's another example:
![image](https://user-images.githubusercontent.com/2524396/64935543-bafc2180-d806-11e9-9e30-08bca24b610c.png)

You can see that the method definition gets covered, but the method body, and the `end` line of the method are both marked as "unreachable". 

Can you shine some light as to the best way to interpret this? Thanks!

**Comment by blakewest** [comment]
To add one more weird thing I'm seeing right now in prod...
![image](https://user-images.githubusercontent.com/2524396/64935947-74a7c200-d808-11e9-90ac-5e7f65415a17.png)

Note that the *comment* is marked as green, which contradicts the earlier statement that such things should be unreachable. Thoughts?

**Comment by kbaum** [comment]
Hi @blakewest. My first thought here is that the source code being read from the file system is not matching up with the data stored in redis. I believe this could happen if one is creating the report from a different version of the code base from what generated the data in the redis instance.

How are you creating the report?

**Comment by blakewest** [comment]
@kbaum we're creating the report simply by mounting the built in web interface to our admin system. I log into the production admin system, and there's a little link (that I made) that takes you to the built in Coverband Web Reporter. The only "wrinkle" to a fully standard setup is that because of some auth and security concerns, we were asked to statically serve the Coverband report files outside of the normal gem path. As in, we copied the reporter files and just stuck them in a static folder of the app. So they haven't been updated for about 4 months since we installed Coverband. 

Which is all to say that I don't believe we're "doing" anything outside of using what comes built in. How does Coverband pull the files? Is there any caching that might prevent it from reading the latest version? Perhaps related... when a new MD5 of a file is warranted due to some code change, does all the old coverage data just go away? And would you see always whatever the production stats are for the latest version, or some combined stats that maybe contains some out-of-date line info?

The version of Coverband is `4.1.1` in case it's helpful

**Comment by danmayer** [comment]
Yeah, this definitely, isn't correct as comments are being marked green... something is out of sync between the recorded hits and the files loaded in the report. I can try to look, but might not be able to get to it for a couple of days.

**Comment by danmayer** [comment]
any chance @blakewest you have multiple environments hitting the same Coverband redis?  

IE you are using a shared redis for dev, staging, and production, that could cause the kinds of issues you are experiencing. 

If you can share your `config/coverband.rb` it could help obviously turn anything secret into `XXYYZ`

> The only "wrinkle" to a fully standard setup is that because of some auth and security concerns, we were asked to statically serve the Coverband report files outside of the normal gem path. As in, we copied the reporter files and just stuck them in a static folder of the app. So they haven't been updated for about 4 months since we installed Coverband.

could you explain this a bit more, sounds like the report files could be out of sync?

**Comment by danmayer** [comment]
another question @blakewest do things look correct locally in development, but you only have these issues on production?

Could you tell us a bit more about your deployment? Heroku? AWS? Docker? capistrano? etc?

**Comment by blakewest** [comment]
@danmayer Good questions... I'll try to answer them
1.) Any chance we're sharing redis? A: Absolutely not. I work for a relatively popular consumer facing app that takes security very seriously. I don't think this is even possible with our infra setup.
2.) We don't have any special config. So there is no `config/coverband`. We do, however, do a "leader election" when our app boots up though so that only one process per cluster runs coverband. But I doubt this is related? We do this because if we ran it for all processes, it would totally swamp the I/O of redis (even with one process, the redis I/O is pinned)
3.) I think my wording was unclear. I'll just paste in exactly what our controller looks like for the web UI...
```ruby
class Admin::CoverbandsController < AdminController
  before_action :require_engineer_role
  skip_before_action :verify_authenticity_token

  def index
    request.env["PATH_INFO"] += "/" if request.path_info == "/admin/code_coverage"
    app = Coverband::Reporters::Web.new
    case request.path_info
    when /.*\.(css|js|gif|png)$/
      publi_folder_path = [Rails.root, 'public', 'vendor', 'coverband', 'public'].join('/')
      file = request.path_info.split('/') - ['..'] # dont allow traversal
      send_file(File.join(publi_folder_path, file[3..-1])) # remove "/admin/code_coverage" from `file`
    else
      self.response = ActionDispatch::Response.new(*app.call(request.env))
      response.close
    end
    return
  end
end
```
When I said we serve the report files statically, I meant literally the coverband gem code that creates reports is served statically. We just basically proxy to the Coverband web UI thing. It's pretty hacky, but it was a security thing because we had to gate access to only engineers, and we couldn't figure out how to do that directly from a mounted rails engine (which was really a cause of some legacy decision on how we handle auth with our admin app... :/) 

4.) Do things look correct in dev? Well, no actually they don't. I'm seeing the same thing. However... and this is interesting, in both dev and prod, I'm just now seeing something really weird...
![image](https://user-images.githubusercontent.com/2524396/65011689-39b99300-d8c9-11e9-9ac3-98a5e42ae781.png)
Both say the last activity recorded was back in June. (Prod says June 20th). Dev says like June 11th or something.

Hmm... that looks like a smoking gun. Though I have no idea how that could be. I just checked our logs, and we def consistently log "Starting coverband...", which gets logged right before we call `         
::Coverband.configure` and `::Coverband.start`. So I'm a bit confused..

Have you seen this or heard of this before? This could definitely be some bug on our side... and if so, I apologize for wasting your time. If you have any tips on what might be happening though, I'm all ears.

**Comment by blakewest** [comment]
I'll also note that we installed Coverband in the app back in April, so everything was cool for 2 months... and there were not major changes since thing (to Coverband stuff), hmm..

**Comment by kbaum** [comment]
> How does Coverband pull the files?

From the file system currently running the report. It basically combines the data in the configured redis instance with the current version of the file.

>  Perhaps related... when a new MD5 of a file is warranted due to some code change, does all the old coverage data just go away?

Yes. The data is overwritten when reported to redis [here](https://github.com/danmayer/coverband/blob/master/lib/coverband/adapters/base.rb#L118).

To debug this, I recommend looking at the data coming from redis from rails console like this:

``` ruby
Coverband.configuration.store.coverage
```
Look at one of the problematic files:

```ruby
[9] pry(main)> Coverband.configuration.store.coverage["./app/models/something.rb"]
=> {"first_updated_at"=>1568722692,
 "last_updated_at"=>1568722692,
 "file_hash"=>"9312438d33db98f9cb04fb7bf07fced5",
 "data"=>[nil, nil, 1, 1, 1, 1, 1, 1, nil, 1, nil, 1, 0, nil, nil, 1, 0, nil, nil, 1, 0, nil, nil]}
```

Check the file hash matches the current version of the file:

```ruby
Digest::MD5.file("./app/models/something.rb").to_s
```

Let us know if that makes sense and what you come back with.

**Comment by danmayer** [comment]
OK, a number of things sound odd @blakewest 

* you don't have any coverband config... So you are using all defaults? So, coverband only finds your redis because of the ENV var `REDIS_URL`?
* there is almost no way Coverband would peg a Redis, the new optional adapter can put a load on it, but if you don't have a coverband config you are using the default Redis adapter, which is extremely low Redis utilization
         * You can test this out by setting up a coverband config and adjusting the `config.background_reporting_sleep_seconds = 120`, the default is 30s so if you adjust it to 120 you should see 4x reduction on hits to Redis
* As @kbaum mentioned, it would be good to check the raw data and the MD5 hash, you can do that in console or you can access that data by adjusting your config... add debug true then you can look at the specific coverage data in redis. `config.web_debug = true`

Given it isn't working on dev, I would debug that first, the bad `last_activity_recorded` makes me think, all Coverband updates to your redis are failing for some reason... Coverband will always try to ensure it doesn't break your server if misconfigured, swallowing all coverband related errors... In development, enable verbose logging and hit any endpoint and watch the logs for awhile to see what is logged related to Coverband.

```
  config.logger = Rails.logger
  # do not set this to true on production it will log a ton of data ;)
  config.verbose = true
```

Let us know what you find, my guess based on the last_activity is that some error is occurring on every Coverband write and hopefully it is obvious when we log out the exception.

**Comment by blakewest** [comment]
Ok, so we did some debugging today. We tracked it back to a commit that happened an hour before our "last activity updated". We had been manually calling `Coverband.start` in an initializer. That commit moved it to happen in a middleware that we'd setup. But that middleware runs so late that all files have been loaded or required by that point, and thus Coverband effectively doesn't run. At least that's our theory now. We're gonna go back to running it in an initializer and hopefully this will solve the problem... 

I apologize for wasting y'alls time here! And thanks so much for all the prompt replies.

**Comment by blakewest** [comment]
Also, thanks for the note on Redis. I'll admit that I hadn't personally seen the stats, and was going off what an infra guy told me when I'd asked him why we couldn't just run Coverband on all our machines always. I'll confirm with him that this is in fact a problem. Maybe he was reading things wrong? One thing to note is that the same Redis instance would be shared across many clusters in our setup, so presumably it wouldn't just be one machine hitting Redis every 30s, but many. But either way, I hear you that once every 30 seconds seems like it would require an absolute ton of machines to max out Redis.

**Comment by danmayer** [comment]
Awesome, glad you could track down that issue... Sounds like a good lead, hopefully you can simplify or fix when it is initialized.

OK, yeah if you are using `require: false` in your Gemfile, and manually calling `Coverband.start` you definitely need it to happen early in the app boot so that your files are loaded.

That being said if you are using traditional Gemfile setup and Rails, you shouldn't have to call `Coverband.start` manually at all? 

Do you all do other stuff to block the normal Coverband middleware from running, so that you can run your custom one?

I am thinking you might have a lot of extra custom code related to coverband, that isn't needed anymore. The old 2.x and 3.x Coverband versions were a bit more complicated to setup, but with the 4.x releases, it shouldn't require much other than adding to your Gemfile and giving it a Redis endpoint (and configuring routing if you want to use the web reporter).

As for the Redis load, yeah if you are sharing a redis with multiple Apps perhaps it just has high load. If you have one Redis server for a cluster of machine that should be fine. On production we have 500+ server processes hitting a single redis instance with Coverband every 30 seconds.

**Comment by kbaum** [comment]
Great news that we figured this out. I still think there is a bug here though. If a file has had no coverage but then has a change made to the file which updates the checksum, the report will show the coverage data for the old version of the file with the new version of the source code. This most often is not an issue has the file is usually covered and when the data is set to redis, this coverage on the new version of the file with the new checksum replaces the old coverage data.

Let me know if that makes sense.

**Comment by danmayer** [comment]
true, if the old file never gets replaced we don't make it clear to the user, so checking the checksum to match before putting in the report would be good... Let's see if we can fix that.

**Comment by danmayer** [comment]
closing as we added the tooltips and there is a ticket for the other issue.

**Comment by jjb** [comment]
tooltip commit: https://github.com/danmayer/coverband/commit/ebe47d068e73b1f9f027b7e4d17d19a49c84a0dc
