### ISSUE TITLE
Error when using simplecov 18.1

### ISSUE THREAD

**Issue by hirowatari** [danmayer/coverband#368]
I upgraded from simplecov 17.1 to 18.1.  Now when I run tests I get the error

```
E, [2020-02-06T15:41:28.180442 #1646] ERROR -- : coverage failed to store
E, [2020-02-06T15:41:28.180546 #1646] ERROR -- : Coverband Error: #<NoMethodError: undefined method `nonzero?' for [:lines, [nil, nil, 1, 1, 1, 1, nil, nil]]:Array> undefined method `nonzero?' for [:lines, [nil, nil, 1, 1, 1, 1, nil, nil]]:Array
```

Is this a coverband issue or simplecov?  Does coverband conflict with the latest simplecov?

**Comment by danmayer** [comment]
did you enable branch support for simplecov? If so that will change what stdlib `Coverage` reports so that coverband can't process it. 

I can look at being able to handle both formats, but for now I would say SimpleCov is for test env and Coverband is for dev,staging,production... So another easy fix would be to put `, require: false` after coverband in your Gemfile. Then in your your `application.rb` you can manually start it in non test environments.

```
Bundler.require(*Rails.groups)
#add after bundler require
require 'coverband' unless Rails.env.test?
```

We have support for oneshot while simplcov does not, so the same sort of error would occur if you enabled oneshot in coverband, simplecov wouldn't be able to parse the output of Coverage... I am sure at some point both tools will be able to process all 3 Coverage formats ;)

**Comment by hirowatari** [comment]
Thanks for the quick response. No I didn't enable branch coverage.

Your solution worked.  It makes sense to not run coverband in test.  Thanks.

**Comment by hirowatari** [comment]
One small addition is that you'll need to edit your routes to avoid referencing coverband in test eg:
`mount Coverband::Reporters::Web.new, at: '/coverage' if defined? Coverband`

**Comment by danmayer** [comment]
thanks for noticing the route issue and adding the comment. I am thinking we can detect this case and log out a warning and then safely ignore it. It seems like a good fix until we add full support.  I am guessing SimpleCov must have enabled by default.

**Comment by danmayer** [comment]
this PR handles the new formats and issues with both Coverband and SimpleCov in the same project https://github.com/danmayer/coverband/pull/371
