### ISSUE TITLE
uninitialized constant Coverband::Reporters::HTMLReport

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#387]
![image](https://user-images.githubusercontent.com/96786/89721033-98d33b00-d9a6-11ea-9d2c-c9414b24ca12.png)

It looks like we are trying to re-define the `Coverband::Reporters::Web.initialize`

https://github.com/danmayer/coverband/blob/78a1da323ecabc6ad780b272034854a5c3700c63/lib/coverband.rb#L116-L126

But for some reason when I debug in pry it seems the old initialize method here is being called:

https://github.com/danmayer/coverband/blob/78a1da323ecabc6ad780b272034854a5c3700c63/lib/coverband/reporters/web.rb#L14-L16

As a result, we are missing some required files.

Any reason why we redefine it in coverband.rb instead of just defining it directly here: 

https://github.com/danmayer/coverband/blob/78a1da323ecabc6ad780b272034854a5c3700c63/lib/coverband/reporters/web.rb#L14-L16

**Comment by danmayer** [comment]
What version are you trying to install... Is this just the latest RC release or master on local path?

I have it up and running without issues nor this error in production.

Not sure what you mean from the lines you linked... Basically, the whole goal is that if you aren't using the web reporter you don't need it...

Because we have the override the normal initialize can't be used, the override will call `init_web`... are you explicitly requiring any files?

I guess there is no harm in having the normal initialize do all the same requires at the override, but I don't understand how you would ever call the normal initialize unless you were requiring it yourself.

**Comment by kbaum** [comment]
> What version are you trying to install... Is this just the latest RC release or master on local path?

Latest master on local path.

> Because we have the override the normal initialize can't be used, the override will call init_web... are you explicitly requiring any files?

I'm sure it's something specific about the way coverband is being required. More info here: https://github.com/danmayer/coverband/pull/388#discussion_r467566735
