### ISSUE TITLE
the report index route does't work with route constraints

### ISSUE THREAD

**Issue by josh-chan** [danmayer/coverband#391]
``` ruby
Rails.application.routes.draw do
  scope :admin, constraints: AdminConstraint.new  do
    mount Coverband::Reporters::Web.new, at: "/coverage"
  end
end
```

``` ruby
class AdminConstraint
  def matches?(request)
    Rails.logger.info "admin request session: #{request.session.inspect}"
    if request.session[:admin_id].blank?
      return false
    end

    if User.find_by(id: request.session[:admin_id])&.admin?
      return true
    end

    false
  end
end

```

the above `request.session.inspect` output `{}` blank.

and when request `/admin/coverage`, an error happen:

```
 NoMethodError (undefined method `[]=' for nil:NilClass):
actionpack (6.0.1) lib/action_dispatch/request/session.rb:230:in `load!' 
actionpack (6.0.1) lib/action_dispatch/request/session.rb:225:in `load_for_write!
actionpack (6.0.1) lib/action_dispatch/request/session.rb:210:in `merge!'
...
```

gem version: 4.2.7, rails: 6.0.3

**Comment by danmayer** [comment]
cool, so I reproduced this in coverband demo see the issue/fix here: https://github.com/coverband-service/coverband_demo/commit/e6ae6f4761807e4a1740b7ee3fea02ff43746753

the fix is to try to use the session before reading it `request.session["init"] = true` seen here https://github.com/coverband-service/coverband_demo/commit/e6ae6f4761807e4a1740b7ee3fea02ff43746753#diff-21497849d8f00507c9c8dcaf6288b136R20

this is a known bug in using sessions in routes I guess, see the bug here: https://github.com/rails/rails/issues/10813

Anyways, hope the examples help but really all of this is outside of coverband so I won't be changing anything in coverband, but hopefully this is a good issue if anyone else hits these kinds of problems.

**Comment by danmayer** [comment]
let me know if this all makes sense @josh-chan and I will close the issue out

**Comment by danmayer** [comment]
OK, I think this one is all set so I am closing it out. Let me know if you need anything else @josh-chan
