### ISSUE TITLE
A question about using Redis HINCRBY command in Lua script for HashRedisStore

### ISSUE THREAD

**Issue by natt-eyre** [danmayer/coverband#430]
Hi there!

Lately I've been researching how your gem works and I really admire the work you did 🙂 
So I came across this Lua script you have, I don't have any experience with Lua and little experience with Redis so I'm maybe missing something. But why do you use Redis HINCRBY command to update a line coverage? I read the docs here https://redis.io/commands/hincrby and they state that this command accepts an increment, but if I understood correctly in your Lua script you send current line coverage as an increment, not a difference between previous line coverage and current one. Did I misunderstand something? 
This is the line that concerns me.
https://github.com/danmayer/coverband/blob/master/lua/lib/persist-coverage.lua#L23

**Comment by danmayer** [comment]
Since @kbaum implemented the lua script and this method he can likely give some better details than I...

Basically we calculate the diff elsewhere in the Ruby code before we call the adapter to store coverage, by the time it is passed to the adapter to save it is only the diff and increment counts that are included.

**Comment by natt-eyre** [comment]
Oh I somehow missed that Delta.results returns the diff. Thanks, I'm closing the issue now.
