### ISSUE TITLE
How do I clear/reset coverage of tracked views?

### ISSUE THREAD

**Issue by dkniffin** [danmayer/coverband#485]
Sorry if this is the wrong place to ask this, but I don't see it documented anywhere. Is there a way to reset the Views Tracker tab of the UI?

**Comment by danmayer** [comment]
yeah it should show at the top of the view tracker index on the web. If you don't see it let me know.

**Comment by dkniffin** [comment]
![Screen Shot 2023-10-10 at 1 26 21 PM](https://github.com/danmayer/coverband/assets/1680080/9aaf9dd4-7508-436c-8cbc-7380b891bc4e)

I don't see it

**Comment by dkniffin** [comment]
Maybe `web_enable_clear` needs to be `true`? Is there a way to do this via command line?

**Comment by danmayer** [comment]
yeah so you do need to configure that in your coverband configuration, we allow turning it off as some teams said folks clicked it without understanding what it does... update your coverband.rb file to set that to true and you should be good to go.

```
          <% if Coverband.configuration.web_enable_clear %>
            <%= button("#{base_path}clear_#{tracker.route}", "reset #{tracker.title} tracker", delete: true) %>
          <% end %>
```

**Comment by dkniffin** [comment]
Okay. I can do that. But it would be nice if there was a rake task to do that

**Comment by danmayer** [comment]
Also, worth noting one of the reasons I don't setup much with Rake or via the CLI anymore is many of the corporate deployments no longer allow access from developer machines, console, production tasks.... So they have been increasingly of limited use due to various security restrictions around accessing production data without auditable code changes / deployment... Anyways, I do see some places it is still very useful or where places allow running rake tasks and recording and auditing the usage.

**Comment by dkniffin** [comment]
@danmayer That looks great! And I had no idea there was route tracking. 🤯  That's good to know!
