### ISSUE TITLE
[feature request] display last posted datetime per line

### ISSUE THREAD

**Issue by FeLvi-zzz** [danmayer/coverband#494]
**Is your feature request related to a problem? Please describe.**
I can recognize how many a line executed, but I cannot recognize when the line executed.

**Describe the solution you'd like**
like this, displaying last posted datetime per line.
"last posted time" is not "last executed time" precisely, but I think it is useful information.
![image](https://github.com/danmayer/coverband/assets/34182539/e9cb6a51-4a76-4ab0-b738-072cffed727e)
PoC: https://github.com/FeLvi-zzz/coverband/pull/1

what do you think?

**Describe alternatives you've considered**
none for now

**Additional context**
none

**Comment by nevinera** [comment]
@danmayer - I came here to make this exact request. Right now the only way to tell if something _becomes_ unused is to reset the data and _wait_. But there are plenty of infrequently used features, so you often need to wait a month or so before you can be confident that any given bit of code is _actually_ dead and removable. That makes the debriding cycle time _very_ long.

If we were able to track the rough last-executed time (or even just date) for each line (and that would likely need to be a configurable option, since it would require more memory), we could just _leave it running_, and we'd always be able to look at code and see if it's dead. The coverage statistics wouldn't really help us, since things that were run a year ago would be listed as 'covered', but I can imagine evolutions of behavior to resolve that as well, later :-)

It looks like they've got a working implementation (supporting only redis hash store), but I'd be happy to put in some extra time to make this a configurable behavior, and support it in additional stores.

**Comment by danmayer** [comment]
yeah this feature exists in a coverband service that we never really ended up launching.... I guess there is a fork with it merged, I can take a look at that and perhaps pull it into all the implementations.

**Comment by danmayer** [comment]
OK, this is in the 6.1.0 release, I still only have it in the HashRedis adapter, but it should surface in the web admin reporting tool.

take a look @nevinera and thanks so much @FeLvi-zzz I pulled your code in just fixing up some merge conflicts
