### ISSUE TITLE
Reporting coverage fails if redis is not configured

### ISSUE THREAD

**Issue by thedrow** [danmayer/coverband#58]
It seems that Coverband.report only works if redis is configured and fails with an exception message if it isn't

```
/Users/omer.katz/.rvm/gems/ruby-2.2.2@mygemset/gems/coverband-1.1/lib/coverband/reporter.rb:104:in `get_current_scov_data_imp': undefined method `smembers' for nil:NilClass (NoMethodError)
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@mygemset/gems/coverband-1.1/lib/coverband/reporter.rb:123:in `report_scov'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@mygemset/gems/coverband-1.1/lib/coverband/reporter.rb:42:in `report'
    from ruby_file.rb:23:in `<main>
```

At the very least I think that the method should fail with a proper message.
I can make a pull request for that if you want to.
There's another option though. Maybe we should allow reporting coverage from the in-memory store if redis is not configured.

**Comment by danmayer** [comment]
hmmm I think a better error message is best... The in memory is only really useful for the tests. Since normally the rake task or console would be in different memory than the web app server it would really never have any useful data. In theory you could use it by booting into console, calling some methods, and in console getting a report which would let yo see the code path of methods called in console, but that doesn't seem like a common use case.
