### ISSUE TITLE
Running baseline in production

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#97]
The coverband README warns against running `rake coverband:baseline` in production. I would like to schedule something like this to run every couple of weeks:

```
rake coverband:clear 
rake coverband:baseline 
```
Whats the danger of running `coverband:baseline` in production?

**Comment by danmayer** [comment]
So basically it comes back to this ticket, where the folks had a checked in file that when loaded would wipe the DB.... o_0

https://github.com/danmayer/coverband/issues/89

Coverband baseline tries to load all files we added some features to prevent that, but basically, you can run the baseline in dev mode (or in a staging environment) or whatever else to get the same results and then still merge it with the runtime data. If you know you don't have any dangerous files you can run it in production or you could try just running it like so `RAILS_ENV=dev rake coverband:baseline`

**Comment by danmayer** [comment]
let me know if that helps or if I should try to make it more clear in the readme

**Comment by lacco** [comment]
Just to clarify my understanding about the baseline: Although the README states that you should not run the rake task on production, we need to have a way to record the baseline.

Running `RAILS_ENV=development rake coverband:baseline` is no option for me because this environment is not set up there. Running `rake coverband:baseline` locally and just passing the production redis options is also not working since our production redis is protected from outside access.

As far as I see the only option for me is to actually run `RAILS_ENV=production rake coverband:baseline` which should not be an issue as long as it's safe to load all files from `/app` and `/lib`?

**Comment by danmayer** [comment]
yes, this is confusing for now especially with the baseline now also stored in Redis it used to be much easier to merge a dev coverage baseline and production coverage data. Long as you don't have any dangerous files it should be safe to run. The next version of Coverband that I am working on will no longer require a baseline at all which should simply all of these issues. It will still take me awhile to get that version out though as I am only working on it a bit here and there.

**Comment by ndbroadbent** [comment]
Reading through [the rake task code](https://github.com/danmayer/coverband/blob/master/lib/coverband/tasks.rb#L20), I can see why that would happen, since it was requiring `/app/**/*.rb` and `./lib/**/*.rb`.

I overrode the rake task in my app and replaced those lines with `Rails.application.eager_load!`. That seems to be working quite well for me. There are some files in `app` and `lib` that weren't eager loaded, but if they're still 0% after some web requests then it would be easier to see that they aren't being used.

**Comment by danmayer** [comment]
PR for Coverband 2.0! Alpha release running on prod for last 2 months. Let me know if there is any last minute feedback, if not I will release later tonight ;) Also, sharing thoughts Future 3.0 roadmap. 

https://github.com/danmayer/coverband/pull/107

As part of the quick move to 3.0 I believe I can just entirely remove the concept of baseline as it is tricky and can require running code on dev and pushing the data to a production data source... I believe a change in mindset to better think of things how StdLib `Coverage` does, should address and resolve this issue once and for all ;) @kbaum @lacco @ndbroadbent

**Comment by danmayer** [comment]
on the master branch all the baseline code has been removed. I will be doing additional testing but that should go out in 2.0.2 although give folks might have automated tasks that call baseline perhaps I should bump to 2.1.0

**Comment by danmayer** [comment]
The baseline feature is removed in the `2.0.2.alpha` release, in testing now... closing this out
